name: Electron Builder Action
author: Leon
description: GitHub Action for building Electron App

inputs:
  build:
    description: Build
    required: true
  project_name:
    description: Project name
    required: true
  github_token:
    description: Github token
    required: true
  project:
    description: Project type
    required: false
  build_script:
    description: Custom build script
    required: false
  working-directory:
    description: Working directory
    required: false
  fontawesome_token:
    description: Fontawesome token
    required: false
  mac_certs:
    description: Base64-encoded code signing certificate for macOS
    required: false
  mac_certs_password:
    description: Password for decrypting `mac_certs`
    required: false
  windows_certs:
    description: Base64-encoded code signing certificate for Windows
    required: false
  windows_certs_password:
    description: Password for decrypting `windows_certs`
    required: false
  ci:
    description: CI check
    required: false
    default: false
  generate_sourcemap:
    description: Generate sourcemap
    required: false
    default: false
  enable_auth:
    description: Enable auth
    required: false
    default: false
  react_app_mixpanel_token:
    description: Mixpanel
    required: false
  premium_editor:
    description: Premium Editor path
    required: false

runs:
  using: node12
  main: index.js

branding:
  icon: upload-cloud
  color: blue
